create table answers
(
    answer_id int8 not null,
    answers   varchar(255)
);
create table question
(
	id 			 	 int8 generated by default as identity,
	question_text 	 varchar(255),
	type_of_question varchar(255),
	primary key (id)
);
create table question_answers
(
	question_id 	 int8 not null,
	question_answers varchar(255)
);
create table quiz
(
    id          int8 generated by default as identity,
    created_on  timestamp,
    username    varchar(255),
    primary key (id)
);
create table refresh_token
(
    id           int8 generated by default as identity,
    created_date timestamp,
    token        varchar(255),
    primary key (id)
);
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);
create table usr
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

alter table if exists usr add constraint UK_dfui7gxngrgwn9ewee3ogtgym unique (username);
alter table if exists answers add constraint FK3y4g6lnwl2etb2ka55jw0bw36 foreign key (answer_id) references quiz;
alter table if exists question_answers add constraint FKj541towvheyqieeidw7a3ewxv foreign key (question_id) references question;
alter table if exists user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;
