create table quiz
(
    id                  int8 generated by default as identity,
    created_on          timestamp,
    eighth_question     varchar(255),
    eleventh_question   oid,
    fifteenth_question  oid,
    fifth_question      varchar(255),
    first_question      varchar(255),
    fourteenth_question oid,
    fourth_question     varchar(255),
    ninth_question      varchar(255),
    second_question     varchar(255),
    seventh_question    varchar(255),
    sixth_question      varchar(255),
    tenth_question      varchar(255),
    third_question      oid,
    thirteenth_question varchar(255),
    twelfth_question    oid,
    username            varchar(255),
    primary key (id)
);
create table refresh_token
(
    id           int8 generated by default as identity,
    created_date timestamp,
    token        varchar(255),
    primary key (id)
);
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);
create table usr
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);
alter table if exists usr drop constraint if exists UK_dfui7gxngrgwn9ewee3ogtgym;
alter table if exists usr add constraint UK_dfui7gxngrgwn9ewee3ogtgym unique (username);
alter table if exists user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;
